### ISSUE TITLE
Issues with flux_bootstrap_git creation and destruction

### ISSUE THREAD

**Issue by Omar-Alkesh** [fluxcd/terraform-provider-flux#479]
### Description

I encountered several issues related to the `flux_bootstrap_git` creation and destruction process. Here are the problems I encountered:

1. **Creation Failure**: The `flux_bootstrap_git` creation fails when the Kubernetes resources already exist.
2. **Destruction Failure**: It also fails to destroy when the resources don't exist.
3. **Race Condition**: Creation and destruction fail when there is a race condition with GitHub.
4. **Frequent Commits and Deployments**: Our repository receives commits and deployments every minute or so.

### Desired Solutions

I have a couple of questions regarding possible solutions:

1. **Separate Repo for flux-system Directory**: Is there a way to place the `flux-system` directory in a separate repository to avoid these issues?
2. **Retry After Failure or Fast-Forward**: Is there a way to force the git push to retry after failure or use the `fast-forward` method to address the non-fast-forward update error?

### Error Details

Here is the error I receive when encountering the git race condition:

```
╷
│ Error: Bootstrap run error
│
│   with module.flux-trunk-1.module.k8s["enabled"].flux_bootstrap_git.flux,
│   on ../modules/fluxv2/k8s/main.tf line 19, in resource "flux_bootstrap_git" "flux":
│   19: resource "flux_bootstrap_git" "flux" {
│
│ failed to push manifests: non-fast-forward update: refs/heads/master
╵
```

Please let me know if you need any additional information or clarification. Thank you!

**Comment by swade1987** [comment]
Hello @Omar-Alkesh  ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

----

I understand your situation, and I want to emphasize a crucial principle when working with Terraform: it's essential to manage all resources through Terraform once they are created by it. This approach ensures consistency and avoids potential conflicts or discrepancies, which could indeed lead to significant challenges down the line.

Terraform is designed to maintain the state of your infrastructure, reflecting the actual resources in your environment. When changes are made outside of Terraform, such as directly deleting or modifying resources, it can lead to a state mismatch. This mismatch often results in Terraform either trying to recreate those resources (assuming they are missing) or failing to apply changes due to unexpected differences between its state and the real-world configuration.

This principle applies not only to Flux but also to any resource managed by any provider within Terraform's ecosystem.

The `flux_bootstrap_git` resource expects a clean cluster ready for bootstrapping, anything pre-existing is going to cause issues.

**Comment by maxwell-gregory** [comment]
@swade1987 We are still encountering this issue specifically when upgrading our provider version from 0.25.8 to 1.1.2

> Additionally, the `flux_bootstrap_git` resource expects a clean cluster ready for bootstrapping. Anything pre-existing is going to cause issues.

If this is true how do we upgrade our provider version? These clusters already have flux installed yet this new provider will only work for a cluster free of Flux?

**Comment by swade1987** [comment]
@maxwell-gregory I haven't tried this migration but a guide was created before I started contributing to the provider. The guide can be found at https://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/migrating-to-resource additionally can I recommend you upgrade to the latest version of the provider which is `1.2.3`

**Comment by swade1987** [comment]
Please keep me posted. Note the next version of the provider will only have `flux_bootstrap_git` resource available.

**Comment by ek24014** [comment]
@swade1987 Hi, I am working with Max and attempted to perform the migration steps suggested, however running into an error with API versions when trying to  terraform import flux_bootstrap_git.this flux-system.

The error is 
**│ Error: Could not get GitRepository flux-system/flux-system
│ 
│ failed to get API group resources: unable to retrieve the complete list of server APIs: source.toolkit.fluxcd.io/v1: the server could not find the requested resource**

When I review "kubectl api-resources" the v1 for sources.toolkit.fluxcd.io and kustomize.toolkit.fluxcd.io are not available.  We are currently on provider 0.25.3 and flux v0.41.2

**Comment by swade1987** [comment]
@ek24014 any chance you could open a new issue please and we can track it there 🙏

**Comment by ek24014** [comment]
@swade1987 looks like that issue has been created 
Terraform fails to import flux_bootstrap_git #554
I will add to there. Thank you!

**Comment by ek24014** [comment]
@swade1987 The suggestion in https://github.com/fluxcd/terraform-provider-flux/issues/554 seems to give us a pass forward. However, when triggering terraform destroy we are running into another error
```
Error: Could not delete Flux
Unable to commit removed file(s): cannot create empty commit: clean working tree
```
